const countries = [
  {
    name: "India",
    code: "IN",
    states: [
      { name: "Andhra Pradesh", code: "AP" },
      { name: "Arunachal Pradesh", code: "AR" },
      { name: "Assam", code: "AS" },
      { name: "Bihar", code: "BR" },
      { name: "Chhattisgarh", code: "CT" },
      { name: "Goa", code: "GA" },
      { name: "Gujarat", code: "GJ" },
      { name: "Haryana", code: "HR" },
      { name: "Himachal Pradesh", code: "HP" },
      { name: "Jharkhand", code: "JH" },
      { name: "Karnataka", code: "KA" },
      { name: "Kerala", code: "KL" },
      { name: "Madhya Pradesh", code: "MP" },
      { name: "Maharashtra", code: "MH" },
      { name: "Manipur", code: "MN" },
      { name: "Meghalaya", code: "ML" },
      { name: "Mizoram", code: "MZ" },
      { name: "Nagaland", code: "NL" },
      { name: "Odisha", code: "OR" },
      { name: "Punjab", code: "PB" },
      { name: "Rajasthan", code: "RJ" },
      { name: "Sikkim", code: "SK" },
      { name: "Tamil Nadu", code: "TN" },
      { name: "Telangana", code: "TS" },
      { name: "Tripura", code: "TR" },
      { name: "Uttar Pradesh", code: "UP" },
      { name: "Uttarakhand", code: "UK" },
      { name: "West Bengal", code: "WB" },
      { name: "Andaman and Nicobar Islands", code: "AN" },
      { name: "Chandigarh", code: "CH" },
      { name: "Dadra and Nagar Haveli and Daman and Diu", code: "DN" },
      { name: "Delhi", code: "DL" },
      { name: "Jammu and Kashmir", code: "JK" },
      { name: "Ladakh", code: "LA" },
      { name: "Lakshadweep", code: "LD" },
      { name: "Puducherry", code: "PY" },
    ],
  },
];

const skills = [
  { name: "JavaScript", category: "technical" },
  { name: "TypeScript", category: "technical" },
  { name: "React", category: "technical" },
  { name: "Next.js", category: "technical" },
  { name: "Node.js", category: "technical" },
  { name: "Python", category: "technical" },
  { name: "Java", category: "technical" },
  { name: "SQL", category: "technical" },
  { name: "PostgreSQL", category: "technical" },
  { name: "MongoDB", category: "technical" },
  { name: "Docker", category: "technical" },
  { name: "Kubernetes", category: "technical" },
  { name: "AWS", category: "technical" },
  { name: "CI/CD", category: "technical" },
  { name: "Git", category: "technical" },
  { name: "Leadership", category: "soft" },
  { name: "Communication", category: "soft" },
  { name: "Team Collaboration", category: "soft" },
  { name: "Problem Solving", category: "soft" },
  { name: "Critical Thinking", category: "soft" },
  { name: "Time Management", category: "soft" },
  { name: "Adaptability", category: "soft" },
  { name: "Creativity", category: "soft" },
  { name: "Project Management", category: "soft" },
  { name: "Mentoring", category: "soft" },
];

module.exports = { countries, skills };
